### ISSUE TITLE
issue with superstruct

### ISSUE THREAD

**Issue by gita-v** [microsoft/license-checker-webpack-plugin#34]
Hi, after I upgraded to webpackv5 I am having some issues: 
webpack - 5.11.1
webpack-cli - 4.3.1

Is this license-checker-webpack-plugin or superstruct issue? The file `Users/gita/code/experimental/node_modules/license-checker-webpack-plugin/node_modules/superstruct/src/struct.ts` does not exist in my repo, so not sure how the error logs make sense. 
Any way to debug? 
I can try and make reproducible repo

```
2021-01-07-15:04:16 1|worker-webpack  | [webpack-cli] Error: 
2021-01-07-15:04:16 1|worker-webpack  |     at new StructError (/Users/gita/code/experimental/node_modules/license-checker-webpack-plugin/node_modules/superstruct/src/struct.ts:77:18)
2021-01-07-15:04:16 1|worker-webpack  |     at validate (/Users/gita/code/experimental/node_modules/license-checker-webpack-plugin/node_modules/superstruct/src/struct.ts:176:19)
2021-01-07-15:04:16 1|worker-webpack  |     at assert (/Users/gita/code/experimental/node_modules/license-checker-webpack-plugin/node_modules/superstruct/src/struct.ts:133:18)
2021-01-07-15:04:16 1|worker-webpack  |     at getOptions (/Users/gita/code/experimental/node_modules/license-checker-webpack-plugin/src/optionsUtils.js:47:3)
2021-01-07-15:04:16 1|worker-webpack  |     at new LicenseCheckerWebpackPlugin (/Users/gita/code/experimental/node_modules/license-checker-webpack-plugin/src/index.js:36:20)
2021-01-07-15:04:16 1|worker-webpack  |     at _createOpenSourceSoftwareLicensePlugin (/Users/gita/code/experimental/modules/browser/webpack_helpers.ts:499:10)
2021-01-07-15:04:16 1|worker-webpack  |     at Object.getDefaultPlugins (/Users/gita/code/experimental/modules/browser/webpack_helpers.ts:205:18)
2021-01-07-15:04:16 1|worker-webpack  |     at generateWebpackConfig (/Users/gita/code/experimental/modules/browser/worker.webpack.config.ts:27:16)
2021-01-07-15:04:16 1|worker-webpack  |     at /Users/gita/code/experimental/node_modules/webpack-cli/lib/webpack-cli.js:792:43
2021-01-07-15:04:16 1|worker-webpack  |     at Array.map (<anonymous>) {
2021-01-07-15:04:16 1|worker-webpack  |   value: 'https://raw.githubusercontent.com/grpc/grpc-web/master/LICENSE',
2021-01-07-15:04:16 1|worker-webpack  |   type: 'never',
2021-01-07-15:04:16 1|worker-webpack  |   path: [ 'override', '@improbable-eng/grpc-web@0.13.0', 'licenseUrl' ],
2021-01-07-15:04:16 1|worker-webpack  |   branch: [
2021-01-07-15:04:16 1|worker-webpack  |     {
2021-01-07-15:04:16 1|worker-webpack  |       filter: /(^.*[/\\]node_modules[/\\]((?:@[^/\\]+[/\\])?(?:[^/\\]+)))/,
2021-01-07-15:04:16 1|worker-webpack  |       allow: '(Apache-2.0 OR BSD-2-Clause OR BSD-3-Clause OR ISC OR MIT OR OFL-1.1 OR Unlicense OR W3C OR Zlib)',
2021-01-07-15:04:16 1|worker-webpack  |       ignore: [Array],
2021-01-07-15:04:16 1|worker-webpack  |       override: [Object],
2021-01-07-15:04:16 1|worker-webpack  |       emitError: true,
2021-01-07-15:04:16 1|worker-webpack  |       outputWriter: [AsyncFunction: outputWriter],
2021-01-07-15:04:16 1|worker-webpack  |       outputFilename: 'OpenSourceSoftwareLicenses-worker.json'
2021-01-07-15:04:16 1|worker-webpack  |     },
2021-01-07-15:04:16 1|worker-webpack  |     {
2021-01-07-15:04:16 1|worker-webpack  |       '@improbable-eng/grpc-web@0.13.0': [Object],
2021-01-07-15:04:16 1|worker-webpack  |     },
2021-01-07-15:04:16 1|worker-webpack  |     {
2021-01-07-15:04:16 1|worker-webpack  |       licenseName: 'Apache-2.0',
2021-01-07-15:04:16 1|worker-webpack  |       licenseUrl: 'https://raw.githubusercontent.com/grpc/grpc-web/master/LICENSE'
2021-01-07-15:04:16 1|worker-webpack  |     },
2021-01-07-15:04:16 1|worker-webpack  |     'https://raw.githubusercontent.com/grpc/grpc-web/master/LICENSE'
2021-01-07-15:04:16 1|worker-webpack  |   ],
2021-01-07-15:04:16 1|worker-webpack  |   failures: [Function: failures]
2021-01-07-15:04:16 1|worker-webpack  | }

```

**Comment by unindented** [comment]
@bz2 @MikeDevice have you ever encountered this issue?

**Comment by bz2** [comment]
The error is not very easy to read (could be adapted to be clearer) - it's saying`licenseUrl` is not valid. That's not part of the normal output, which only includes `licenseName` and `licenseText`. If override should be allowed to specify arbitrary properties, the validation definition can change.

**Comment by gita-v** [comment]
Ahhhhh thank you!! And thanks for getting back to me so soon :)
